name: uot_students
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  http: ^1.3.0
  search_choices: ^2.3.1
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


